-- 코드를 작성해주세요
SELECT *
FROM
(SELECT
    CASE
        WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AND
            SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
        WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') THEN 'C'
        END AS GRADE, ID, EMAIL
FROM DEVELOPERS) AS SUB
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID