SELECT SUM(C.SCORE) AS SCORE, B.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
FROM HR_DEPARTMENT A
LEFT JOIN HR_EMPLOYEES B ON A.DEPT_ID = B.DEPT_ID
LEFT JOIN HR_GRADE C ON B.EMP_NO = C.EMP_NO
WHERE C.YEAR = '2022'
GROUP BY B.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
HAVING SUM(C.SCORE) = 
    (
    SELECT MAX(SUB.TOTAL_SCORE)
    FROM
        (SELECT SUM(C.SCORE) AS TOTAL_SCORE
        FROM HR_DEPARTMENT A
        LEFT JOIN HR_EMPLOYEES B ON A.DEPT_ID = B.DEPT_ID
        LEFT JOIN HR_GRADE C ON B.EMP_NO = C.EMP_NO
        WHERE C.YEAR = '2022'
        GROUP BY B.EMP_NO, B.EMP_NAME, B.POSITION, B.EMAIL
        ) AS SUB
    );
